#pragma once

#include <cstdio>
#include <functional>
#include <string>
#include <vector>

// ---------------------------------------------------------------------------
// Minimal test runner — no external dependencies, C++17 only.
//
// Syntax mirrors Google Test:
//
//   TEST(DescriptiveName)
//   {
//       CHECK(expr);
//       CHECK_EQ(a, b);
//   }
//
//   int main() { return sw::test::runAll(); }
//
// How it works:
//   TEST(Name) expands to a struct definition + a static registration object,
//   then opens the TestBody() method body — exactly like GTest does internally.
//   The closing brace of the user's block closes TestBody().
// ---------------------------------------------------------------------------

namespace sw::test
{
	// Base class for all test cases generated by the TEST() macro.
	struct TestBase
	{
		virtual void TestBody() = 0;
		virtual ~TestBase() = default;
	};

	struct Registration
	{
		std::string                      name;
		std::function<TestBase*()>       factory;
	};

	inline int& failCount()  { static int n = 0; return n; }
	inline int& checkCount() { static int n = 0; return n; }

	inline std::vector<Registration>& registry()
	{
		static std::vector<Registration> v;
		return v;
	}

	inline void registerTest(std::string name, std::function<TestBase*()> factory)
	{
		registry().push_back({std::move(name), std::move(factory)});
	}

	inline void checkImpl(bool ok, const char* expr, const char* file, int line)
	{
		++checkCount();
		if (!ok)
		{
			++failCount();
			std::fprintf(stderr, "  FAIL  %s:%d  CHECK(%s)\n", file, line, expr);
		}
	}

	inline int runAll()
	{
		int passed = 0;
		int failed = 0;

		for (auto& reg : registry())
		{
			int beforeFails = failCount();
			TestBase* tc = reg.factory();
			tc->TestBody();
			delete tc;

			if (failCount() == beforeFails)
			{
				std::printf("  OK    %s\n", reg.name.c_str());
				++passed;
			}
			else
			{
				std::printf("  FAIL  %s\n", reg.name.c_str());
				++failed;
			}
		}

		std::printf("\n%d passed, %d failed (%d checks total)\n",
		            passed, failed, checkCount());
		return failed > 0 ? 1 : 0;
	}
} // namespace sw::test

// ---------------------------------------------------------------------------
// Assertion macros
// ---------------------------------------------------------------------------

#define CHECK(expr) \
	sw::test::checkImpl(static_cast<bool>(expr), #expr, __FILE__, __LINE__)

#define CHECK_EQ(a, b) \
	sw::test::checkImpl((a) == (b), #a " == " #b, __FILE__, __LINE__)

#define CHECK_NE(a, b) \
	sw::test::checkImpl((a) != (b), #a " != " #b, __FILE__, __LINE__)

// ---------------------------------------------------------------------------
// TEST(Name) macro — GTest-style, no END_TEST needed.
//
// Expands to:
//   struct _Test_Name : sw::test::TestBase {
//       void TestBody() override;
//       static sw::test::TestBase* _factory() { return new _Test_Name; }
//   };
//   static const bool _reg_Name = (sw::test::registerTest("Name", _Test_Name::_factory), true);
//   void _Test_Name::TestBody()
//   {
//       /* user code */
//   }
// ---------------------------------------------------------------------------

#define SW_TEST_CONCAT_(a, b) a##b
#define SW_TEST_CONCAT(a, b)  SW_TEST_CONCAT_(a, b)
#define SW_TEST_CLASS(name)   SW_TEST_CONCAT(_SwTest_, name)

#define TEST(name)                                                              \
	struct SW_TEST_CLASS(name) : sw::test::TestBase                             \
	{                                                                           \
		void TestBody() override;                                               \
		static sw::test::TestBase* _factory()                                   \
		{                                                                       \
			return new SW_TEST_CLASS(name);                                     \
		}                                                                       \
	};                                                                          \
	static const bool SW_TEST_CONCAT(_sw_reg_, name) =                         \
		(sw::test::registerTest(#name, SW_TEST_CLASS(name)::_factory), true);   \
	void SW_TEST_CLASS(name)::TestBody()
